### PR TITLE
Implement support for Generic.Rep

### PR DESCRIPTION
**Pull request by albertov**
Addresses #33. purs seems to be able to compile the code that [hs-mapnik-purs](https://github.com/albertov/hs-mapnik/blob/purs/purs/GeneratePS.hs) generates, which includes a Data.StrMap!

Apart from this, I 'm not sure it doesn't break anything else so please test before an eventual merge.

### CODE REVIEW

**Comment by eskimor** [comment]
Thank you! Will check!

**Comment by eskimor** [comment]
Ok, I don't really understand how this is still compatible with purescript-argonaut-generic codecs and how this works, even if you drop the Generic requirement for type parameters. Because purescript-argonaut-generic codecs walks through the complete representation, also of contained types (thus they need to be Generic). This sucks at times, but was the only way back then.

**Comment by albertov** [comment]
This makes the representation no longer compatible with argonaut but https://github.com/paf31/purescript-foreign-generic should be a drop-in replacement.

If compatibility with argonaut is still desired, maybe we could generate both instances or make it configurable with a flag?

**Comment by eskimor** [comment]
If we can have both instances this would be best at least for a smooth transition. Also I am not sure how compatible purescript-foreign-generic is with Aeson. Also users might have taken advantage of argonaut-generic-codecs customization options, so at least for them this would not be a drop in replacement.

**Comment by fosskers** [comment]
Any updates with this?

**Comment by fosskers** [comment]
My bad - my latest PR broke this, since it changed the structure of `SumType` and a few related functions.

**Pull request closed without merging**
