### PR TITLE
Use newtype where possible

### LINKED ISSUE #10: Generate newtype instead of data where possible.

### PR DESCRIPTION
**Pull request by alexbiehl**
Fixes #10

### CODE REVIEW

**Comment by eskimor** [comment]
looks good - but travis complains and I belive the test suit needs adoption?

**Comment by alexbiehl** [comment]
Ah, sorry. Some artificats went in too!

**Comment by sectore** [comment]
@eskimor Any chance to merge this? Would really appreciate that :)

**Comment by eskimor** [comment]
Test suits needs to be fixed, I believe @alexbiehl is on it?

**Comment by alexbiehl** [comment]
@eskimor Yes, I extended the test suite.

**Comment by eskimor** [comment]
I completely missed, that you did that already. :-S Thanks!

**Comment by eskimor** [comment]
Thank you! Awesome!

**Pull request merged**
