### PR TITLE
Lenses for newtypes and single-constructor data-types.

### PR DESCRIPTION
**Pull request by krisajenkins**
As it stands:

```haskell
newtype SomeType = SomeType Int
```

...doesn't get a lens, while:

```haskell
data SomeType = SomeType Int
```

...gets a Prism, where a Lens would be a better choice. This patch adds the code and tests to improve that. :-)

### CODE REVIEW

**Comment by boothead** [comment]
This looks good. I think we have two slightly overlapping PRs at the same time though.
 #31 adds the feature requested in #30, which might mean that the lenses for newtypes aren't required here.

Perhaps the easiest thing would be to merge these two PRs together, and prefer the `_Newtype` isos from #31 over the newtype lens added by this PR?

**Comment by boothead** [comment]
In fact, now that we have [prop](https://pursuit.purescript.org/packages/purescript-profunctor-lenses/3.2.0/docs/Data.Lens.Record#v:prop), which uses proxys of the symbol of the record lable to give us type safe generic record lenses, perhaps we should re-think the generation of lenses altogether.

**Comment by tippenein** [comment]
This is nice! I'll gladly close #31 in favor of this.

I could see wanting Newtype deriving, but your lens over newtypes pretty much takes care of my use-case.

@boothead I mainly used prop because it was shorter to type and easier to check the codegen. The usage is the same if I understand correctly

**Comment by eskimor** [comment]
Do I understand the code correctly, that newtypes now would get a lens but single constructor data definitions still a prism? But lenses to it's fields? So we have different code gen for newtype and single constructor data defintions? Is this desirable, shouldn't we have a prism for such data definitions as well? Or do we want a prism, because more constructors could be added - so code would not need to be changed?

In any case, nice work! I also like the added test cases - it makes review far easier!

**Comment by eskimor** [comment]
Ok, if I understood correctly, you are still working on this. Please notify me when you think it is ready for merge! Thank you!

**Comment by boothead** [comment]
Looks good to me!

**Comment by eskimor** [comment]
looks good to me too! Do I get it right that this is a breaking change, as prisms for single constructor data got removed?

Thank  you for the nice work!

**Comment by eskimor** [comment]
> The single constructor prisms are now Isos, but type inference should make that invisible.

Yeah, I see that now. Perfect, so a non breaking change it is ;-)



> Thanks for merging it so fast! :-D

Well, if a PR has high quality and others like @boothead take the time for reviewing the changes in addition to me, then fast merging is easy ;-)

**Pull request merged**
